// Code generated by protoc-gen-go.
// source: model.proto
// DO NOT EDIT!

/*
Package model is a generated protocol buffer package.

It is generated from these files:
	model.proto

It has these top-level messages:
	Instance
	Resource
	NoneTemplate
	VMTemplate
*/
package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResourceType int32

const (
	ResourceType_NONE ResourceType = 0
	ResourceType_VM   ResourceType = 1
)

var ResourceType_name = map[int32]string{
	0: "NONE",
	1: "VM",
}
var ResourceType_value = map[string]int32{
	"NONE": 0,
	"VM":   1,
}

func (x ResourceType) String() string {
	return proto.EnumName(ResourceType_name, int32(x))
}
func (ResourceType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ResourceState int32

const (
	ResourceState_RESOURCE_REGISTERED   ResourceState = 0
	ResourceState_RESOURCE_UNREGISTERED ResourceState = 1
)

var ResourceState_name = map[int32]string{
	0: "RESOURCE_REGISTERED",
	1: "RESOURCE_UNREGISTERED",
}
var ResourceState_value = map[string]int32{
	"RESOURCE_REGISTERED":   0,
	"RESOURCE_UNREGISTERED": 1,
}

func (x ResourceState) String() string {
	return proto.EnumName(ResourceState_name, int32(x))
}
func (ResourceState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Instance struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ExecutorId string `protobuf:"bytes,2,opt,name=executor_id,json=executorId" json:"executor_id,omitempty"`
	ResourceId string `protobuf:"bytes,3,opt,name=resource_id,json=resourceId" json:"resource_id,omitempty"`
}

func (m *Instance) Reset()                    { *m = Instance{} }
func (m *Instance) String() string            { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()               {}
func (*Instance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Instance) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Instance) GetExecutorId() string {
	if m != nil {
		return m.ExecutorId
	}
	return ""
}

func (m *Instance) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

type Resource struct {
	Id    string        `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type  ResourceType  `protobuf:"varint,2,opt,name=type,enum=model.ResourceType" json:"type,omitempty"`
	State ResourceState `protobuf:"varint,3,opt,name=state,enum=model.ResourceState" json:"state,omitempty"`
	// Types that are valid to be assigned to Template:
	//	*Resource_None
	//	*Resource_Vm
	Template isResource_Template `protobuf_oneof:"Template"`
}

func (m *Resource) Reset()                    { *m = Resource{} }
func (m *Resource) String() string            { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()               {}
func (*Resource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type isResource_Template interface {
	isResource_Template()
}

type Resource_None struct {
	None *NoneTemplate `protobuf:"bytes,500,opt,name=none,oneof"`
}
type Resource_Vm struct {
	Vm *VMTemplate `protobuf:"bytes,501,opt,name=vm,oneof"`
}

func (*Resource_None) isResource_Template() {}
func (*Resource_Vm) isResource_Template()   {}

func (m *Resource) GetTemplate() isResource_Template {
	if m != nil {
		return m.Template
	}
	return nil
}

func (m *Resource) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Resource) GetType() ResourceType {
	if m != nil {
		return m.Type
	}
	return ResourceType_NONE
}

func (m *Resource) GetState() ResourceState {
	if m != nil {
		return m.State
	}
	return ResourceState_RESOURCE_REGISTERED
}

func (m *Resource) GetNone() *NoneTemplate {
	if x, ok := m.GetTemplate().(*Resource_None); ok {
		return x.None
	}
	return nil
}

func (m *Resource) GetVm() *VMTemplate {
	if x, ok := m.GetTemplate().(*Resource_Vm); ok {
		return x.Vm
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Resource) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Resource_OneofMarshaler, _Resource_OneofUnmarshaler, _Resource_OneofSizer, []interface{}{
		(*Resource_None)(nil),
		(*Resource_Vm)(nil),
	}
}

func _Resource_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Resource)
	// Template
	switch x := m.Template.(type) {
	case *Resource_None:
		b.EncodeVarint(500<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.None); err != nil {
			return err
		}
	case *Resource_Vm:
		b.EncodeVarint(501<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Vm); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Resource.Template has unexpected type %T", x)
	}
	return nil
}

func _Resource_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Resource)
	switch tag {
	case 500: // Template.none
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NoneTemplate)
		err := b.DecodeMessage(msg)
		m.Template = &Resource_None{msg}
		return true, err
	case 501: // Template.vm
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(VMTemplate)
		err := b.DecodeMessage(msg)
		m.Template = &Resource_Vm{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Resource_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Resource)
	// Template
	switch x := m.Template.(type) {
	case *Resource_None:
		s := proto.Size(x.None)
		n += proto.SizeVarint(500<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Resource_Vm:
		s := proto.Size(x.Vm)
		n += proto.SizeVarint(501<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type NoneTemplate struct {
}

func (m *NoneTemplate) Reset()                    { *m = NoneTemplate{} }
func (m *NoneTemplate) String() string            { return proto.CompactTextString(m) }
func (*NoneTemplate) ProtoMessage()               {}
func (*NoneTemplate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type VMTemplate struct {
	Vcpu             int32  `protobuf:"varint,1,opt,name=vcpu" json:"vcpu,omitempty"`
	MemoryGb         int32  `protobuf:"varint,2,opt,name=memory_gb,json=memoryGb" json:"memory_gb,omitempty"`
	ImageTemplateUri string `protobuf:"bytes,3,opt,name=image_template_uri,json=imageTemplateUri" json:"image_template_uri,omitempty"`
}

func (m *VMTemplate) Reset()                    { *m = VMTemplate{} }
func (m *VMTemplate) String() string            { return proto.CompactTextString(m) }
func (*VMTemplate) ProtoMessage()               {}
func (*VMTemplate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *VMTemplate) GetVcpu() int32 {
	if m != nil {
		return m.Vcpu
	}
	return 0
}

func (m *VMTemplate) GetMemoryGb() int32 {
	if m != nil {
		return m.MemoryGb
	}
	return 0
}

func (m *VMTemplate) GetImageTemplateUri() string {
	if m != nil {
		return m.ImageTemplateUri
	}
	return ""
}

func init() {
	proto.RegisterType((*Instance)(nil), "model.Instance")
	proto.RegisterType((*Resource)(nil), "model.Resource")
	proto.RegisterType((*NoneTemplate)(nil), "model.NoneTemplate")
	proto.RegisterType((*VMTemplate)(nil), "model.VMTemplate")
	proto.RegisterEnum("model.ResourceType", ResourceType_name, ResourceType_value)
	proto.RegisterEnum("model.ResourceState", ResourceState_name, ResourceState_value)
}

func init() { proto.RegisterFile("model.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x92, 0x5f, 0x8b, 0xd3, 0x40,
	0x14, 0xc5, 0x9b, 0x98, 0x2c, 0xd9, 0xdb, 0x35, 0xc4, 0x59, 0xc5, 0x88, 0xc8, 0x2e, 0x41, 0x50,
	0x82, 0xb4, 0xb0, 0x7e, 0x83, 0xad, 0xa1, 0xe6, 0xa1, 0x29, 0x4c, 0xff, 0x3c, 0x88, 0x10, 0xf2,
	0xe7, 0xd2, 0x06, 0x3b, 0x99, 0x90, 0x4c, 0x42, 0xfb, 0x21, 0xfd, 0x36, 0xfa, 0x2e, 0x9d, 0x24,
	0x35, 0xba, 0x6f, 0x73, 0xcf, 0xf9, 0x71, 0x66, 0xee, 0x61, 0x60, 0xcc, 0x78, 0x8a, 0x87, 0x49,
	0x51, 0x72, 0xc1, 0x89, 0x2e, 0x07, 0xe7, 0x3b, 0x18, 0x7e, 0x5e, 0x89, 0x28, 0x4f, 0x90, 0x98,
	0xa0, 0x66, 0xa9, 0xad, 0xdc, 0x2b, 0x1f, 0xaf, 0xa9, 0x9a, 0xa5, 0xe4, 0x0e, 0xc6, 0x78, 0xc4,
	0xa4, 0x16, 0xbc, 0x0c, 0xb3, 0xd4, 0x56, 0xa5, 0x01, 0xbd, 0xe4, 0x4b, 0xa0, 0xc4, 0x8a, 0xd7,
	0x65, 0x82, 0x67, 0xe0, 0x59, 0x0b, 0xf4, 0x92, 0x9f, 0x3a, 0x3f, 0x15, 0x30, 0x68, 0x37, 0x3e,
	0x89, 0xff, 0x00, 0x9a, 0x38, 0x15, 0x28, 0x73, 0xcd, 0x87, 0xdb, 0x49, 0xfb, 0xba, 0x1e, 0x5f,
	0x9f, 0x0a, 0xa4, 0x12, 0x20, 0x2e, 0xe8, 0x95, 0x88, 0x04, 0xca, 0x0b, 0xcc, 0x87, 0x97, 0xff,
	0x91, 0xab, 0xb3, 0x47, 0x5b, 0x84, 0xb8, 0xa0, 0xe5, 0x3c, 0x47, 0xfb, 0xd7, 0x99, 0x1d, 0x5f,
	0x52, 0x03, 0x9e, 0xe3, 0x1a, 0x59, 0x71, 0x88, 0x04, 0x7e, 0x1d, 0x51, 0xc9, 0x90, 0xf7, 0xa0,
	0x36, 0xcc, 0xfe, 0xdd, 0x92, 0x2f, 0x3a, 0x72, 0xbb, 0x18, 0x70, 0x6a, 0xc3, 0x1e, 0x01, 0x8c,
	0x5e, 0x71, 0x4c, 0xb8, 0x19, 0x26, 0x39, 0x3f, 0x00, 0xfe, 0xf2, 0x84, 0x80, 0xd6, 0x24, 0x45,
	0x2d, 0x57, 0xd4, 0xa9, 0x3c, 0x93, 0xb7, 0x70, 0xcd, 0x90, 0xf1, 0xf2, 0x14, 0xee, 0x62, 0xb9,
	0xa9, 0x4e, 0x8d, 0x56, 0x98, 0xc7, 0xe4, 0x13, 0x90, 0x8c, 0x45, 0x3b, 0x0c, 0x45, 0x17, 0x11,
	0xd6, 0x65, 0xd6, 0xd5, 0x68, 0x49, 0xa7, 0xcf, 0xde, 0x94, 0x99, 0x7b, 0x0f, 0x37, 0xc3, 0x72,
	0x88, 0x01, 0x5a, 0xb0, 0x0c, 0x3c, 0x6b, 0x44, 0xae, 0x40, 0xdd, 0x2e, 0x2c, 0xc5, 0x9d, 0xc1,
	0xf3, 0x7f, 0x4a, 0x21, 0xaf, 0xe1, 0x96, 0x7a, 0xab, 0xe5, 0x86, 0xce, 0xbc, 0x90, 0x7a, 0x73,
	0x7f, 0xb5, 0xf6, 0xa8, 0xf7, 0xc5, 0x1a, 0x91, 0x37, 0xf0, 0xea, 0x62, 0x6c, 0x82, 0x81, 0xa5,
	0x3c, 0xde, 0x7d, 0x7b, 0xb7, 0xcb, 0xc4, 0xbe, 0x8e, 0x27, 0x09, 0x67, 0xd3, 0xe8, 0x58, 0xed,
	0xa7, 0xbc, 0xc0, 0xbc, 0x49, 0x93, 0xa9, 0x6c, 0x28, 0xbe, 0x92, 0x1f, 0xe8, 0xf3, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x01, 0x48, 0x47, 0x3c, 0x4f, 0x02, 0x00, 0x00,
}
