// Code generated by protoc-gen-go.
// source: v1.proto
// DO NOT EDIT!

/*
Package openvdc is a generated protocol buffer package.

It is generated from these files:
        v1.proto

It has these top-level messages:
        RunRequest
        RunReply
*/
package openvdc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
        context "golang.org/x/net/context"
        grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
//const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RunRequest struct {
        ImageName string `protobuf:"bytes,1,opt,name=imageName" json:"imageName,omitempty"`
	HostName  string `protobuf:"bytes,2,opt,name=hostName" json:"hostName,omitempty"`
}

func (m *RunRequest) Reset()                    { *m = RunRequest{} }
func (m *RunRequest) String() string            { return proto.CompactTextString(m) }
func (*RunRequest) ProtoMessage()               {}
func (*RunRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RunReply struct {
}

func (m *RunReply) Reset()                    { *m = RunReply{} }
func (m *RunReply) String() string            { return proto.CompactTextString(m) }
func (*RunReply) ProtoMessage()               {}
func (*RunReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
        proto.RegisterType((*RunRequest)(nil), "openvdc.RunRequest")
        proto.RegisterType((*RunReply)(nil), "openvdc.RunReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Instance service

type InstanceClient interface {
        Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunReply, error)
}

type instanceClient struct {
        cc *grpc.ClientConn
}

func NewInstanceClient(cc *grpc.ClientConn) InstanceClient {
        return &instanceClient{cc}
}

func (c *instanceClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunReply, error) {
        out := new(RunReply)
        err := grpc.Invoke(ctx, "/openvdc.Instance/Run", in, out, c.cc, opts...)
        if err != nil {
                return nil, err
        }
        return out, nil
}

// Server API for Instance service

type InstanceServer interface {
        Run(context.Context, *RunRequest) (*RunReply, error)
}

func RegisterInstanceServer(s *grpc.Server, srv InstanceServer) {
        s.RegisterService(&_Instance_serviceDesc, srv)
}

func _Instance_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
        in := new(RunRequest)
        if err := dec(in); err != nil {
                return nil, err
        }
        if interceptor == nil {
                return srv.(InstanceServer).Run(ctx, in)
        }
        info := &grpc.UnaryServerInfo{
                Server:     srv,
                FullMethod: "/openvdc.Instance/Run",
        }
        handler := func(ctx context.Context, req interface{}) (interface{}, error) {
                return srv.(InstanceServer).Run(ctx, req.(*RunRequest))
        }
        return interceptor(ctx, in, info, handler)
}

var _Instance_serviceDesc = grpc.ServiceDesc{
        ServiceName: "openvdc.Instance",
        HandlerType: (*InstanceServer)(nil),
        Methods: []grpc.MethodDesc{
                {
                        MethodName: "Run",
                        Handler:    _Instance_Run_Handler,
                },
        },
        Streams:  []grpc.StreamDesc{},
        Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("v1.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
         // 144 bytes of a gzipped FileDescriptorProto
         0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x28, 0x33, 0xd4, 0x2b,
         0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x2f, 0x48, 0xcd, 0x2b, 0x4b, 0x49, 0x56, 0x72, 0xe3,
         0xe2, 0x0a, 0x2a, 0xcd, 0x0b, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe1, 0xe2, 0xcc,
         0xcc, 0x4d, 0x4c, 0x4f, 0xf5, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x42,
         0x08, 0x08, 0x49, 0x71, 0x71, 0x64, 0xe4, 0x17, 0x97, 0x80, 0x25, 0x99, 0xc0, 0x92, 0x70, 0xbe,
         0x12, 0x17, 0x17, 0x07, 0xd8, 0x9c, 0x82, 0x9c, 0x4a, 0x23, 0x6b, 0x2e, 0x0e, 0xcf, 0xbc, 0xe2,
         0x92, 0xc4, 0xbc, 0xe4, 0x54, 0x21, 0x7d, 0x2e, 0xe6, 0xa0, 0xd2, 0x3c, 0x21, 0x61, 0x3d, 0xa8,
         0x85, 0x7a, 0x08, 0xdb, 0xa4, 0x04, 0x51, 0x05, 0x0b, 0x72, 0x2a, 0x95, 0x18, 0x92, 0xd8, 0xc0,
         0x0e, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xcd, 0x5c, 0xf8, 0xb1, 0xac, 0x00, 0x00, 0x00,
}

