// Code generated by protoc-gen-go.
// source: v1.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	v1.proto

It has these top-level messages:
	RunRequest
	RunReply
	StopTaskRequest
	StopTaskReply
	CreateRequest
	CreateReply
	StartRequest
	StartReply
	ResourceRequest
	ResourceReply
	ResourceIDRequest
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import model "github.com/axsh/openvdc/model"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RunRequest struct {
	ImageName string `protobuf:"bytes,1,opt,name=imageName" json:"imageName,omitempty"`
	HostName  string `protobuf:"bytes,2,opt,name=hostName" json:"hostName,omitempty"`
	TaskType  string `protobuf:"bytes,3,opt,name=taskType" json:"taskType,omitempty"`
}

func (m *RunRequest) Reset()                    { *m = RunRequest{} }
func (m *RunRequest) String() string            { return proto.CompactTextString(m) }
func (*RunRequest) ProtoMessage()               {}
func (*RunRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RunRequest) GetImageName() string {
	if m != nil {
		return m.ImageName
	}
	return ""
}

func (m *RunRequest) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *RunRequest) GetTaskType() string {
	if m != nil {
		return m.TaskType
	}
	return ""
}

type RunReply struct {
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
	ResourceId string `protobuf:"bytes,2,opt,name=resource_id,json=resourceId" json:"resource_id,omitempty"`
}

func (m *RunReply) Reset()                    { *m = RunReply{} }
func (m *RunReply) String() string            { return proto.CompactTextString(m) }
func (*RunReply) ProtoMessage()               {}
func (*RunReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RunReply) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *RunReply) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

type StopTaskRequest struct {
	HostName string `protobuf:"bytes,1,opt,name=hostName" json:"hostName,omitempty"`
	TaskType string `protobuf:"bytes,2,opt,name=taskType" json:"taskType,omitempty"`
}

func (m *StopTaskRequest) Reset()                    { *m = StopTaskRequest{} }
func (m *StopTaskRequest) String() string            { return proto.CompactTextString(m) }
func (*StopTaskRequest) ProtoMessage()               {}
func (*StopTaskRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *StopTaskRequest) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *StopTaskRequest) GetTaskType() string {
	if m != nil {
		return m.TaskType
	}
	return ""
}

type StopTaskReply struct {
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
}

func (m *StopTaskReply) Reset()                    { *m = StopTaskReply{} }
func (m *StopTaskReply) String() string            { return proto.CompactTextString(m) }
func (*StopTaskReply) ProtoMessage()               {}
func (*StopTaskReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *StopTaskReply) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

type CreateRequest struct {
	ResourceId string `protobuf:"bytes,1,opt,name=resource_id,json=resourceId" json:"resource_id,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateRequest) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

type CreateReply struct {
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
}

func (m *CreateReply) Reset()                    { *m = CreateReply{} }
func (m *CreateReply) String() string            { return proto.CompactTextString(m) }
func (*CreateReply) ProtoMessage()               {}
func (*CreateReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreateReply) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

type StartRequest struct {
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
}

func (m *StartRequest) Reset()                    { *m = StartRequest{} }
func (m *StartRequest) String() string            { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()               {}
func (*StartRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *StartRequest) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

type StartReply struct {
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
}

func (m *StartReply) Reset()                    { *m = StartReply{} }
func (m *StartReply) String() string            { return proto.CompactTextString(m) }
func (*StartReply) ProtoMessage()               {}
func (*StartReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *StartReply) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

type ResourceRequest struct {
	// Types that are valid to be assigned to Template:
	//	*ResourceRequest_None
	//	*ResourceRequest_Vm
	Template isResourceRequest_Template `protobuf_oneof:"Template"`
}

func (m *ResourceRequest) Reset()                    { *m = ResourceRequest{} }
func (m *ResourceRequest) String() string            { return proto.CompactTextString(m) }
func (*ResourceRequest) ProtoMessage()               {}
func (*ResourceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type isResourceRequest_Template interface {
	isResourceRequest_Template()
}

type ResourceRequest_None struct {
	None *model.NoneTemplate `protobuf:"bytes,500,opt,name=none,oneof"`
}
type ResourceRequest_Vm struct {
	Vm *model.VMTemplate `protobuf:"bytes,501,opt,name=vm,oneof"`
}

func (*ResourceRequest_None) isResourceRequest_Template() {}
func (*ResourceRequest_Vm) isResourceRequest_Template()   {}

func (m *ResourceRequest) GetTemplate() isResourceRequest_Template {
	if m != nil {
		return m.Template
	}
	return nil
}

func (m *ResourceRequest) GetNone() *model.NoneTemplate {
	if x, ok := m.GetTemplate().(*ResourceRequest_None); ok {
		return x.None
	}
	return nil
}

func (m *ResourceRequest) GetVm() *model.VMTemplate {
	if x, ok := m.GetTemplate().(*ResourceRequest_Vm); ok {
		return x.Vm
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ResourceRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ResourceRequest_OneofMarshaler, _ResourceRequest_OneofUnmarshaler, _ResourceRequest_OneofSizer, []interface{}{
		(*ResourceRequest_None)(nil),
		(*ResourceRequest_Vm)(nil),
	}
}

func _ResourceRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ResourceRequest)
	// Template
	switch x := m.Template.(type) {
	case *ResourceRequest_None:
		b.EncodeVarint(500<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.None); err != nil {
			return err
		}
	case *ResourceRequest_Vm:
		b.EncodeVarint(501<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Vm); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ResourceRequest.Template has unexpected type %T", x)
	}
	return nil
}

func _ResourceRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ResourceRequest)
	switch tag {
	case 500: // Template.none
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(model.NoneTemplate)
		err := b.DecodeMessage(msg)
		m.Template = &ResourceRequest_None{msg}
		return true, err
	case 501: // Template.vm
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(model.VMTemplate)
		err := b.DecodeMessage(msg)
		m.Template = &ResourceRequest_Vm{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ResourceRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ResourceRequest)
	// Template
	switch x := m.Template.(type) {
	case *ResourceRequest_None:
		s := proto.Size(x.None)
		n += proto.SizeVarint(500<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ResourceRequest_Vm:
		s := proto.Size(x.Vm)
		n += proto.SizeVarint(501<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ResourceReply struct {
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
}

func (m *ResourceReply) Reset()                    { *m = ResourceReply{} }
func (m *ResourceReply) String() string            { return proto.CompactTextString(m) }
func (*ResourceReply) ProtoMessage()               {}
func (*ResourceReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ResourceReply) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type ResourceIDRequest struct {
	// Types that are valid to be assigned to Key:
	//	*ResourceIDRequest_ID
	//	*ResourceIDRequest_Name
	Key isResourceIDRequest_Key `protobuf_oneof:"Key"`
}

func (m *ResourceIDRequest) Reset()                    { *m = ResourceIDRequest{} }
func (m *ResourceIDRequest) String() string            { return proto.CompactTextString(m) }
func (*ResourceIDRequest) ProtoMessage()               {}
func (*ResourceIDRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type isResourceIDRequest_Key interface {
	isResourceIDRequest_Key()
}

type ResourceIDRequest_ID struct {
	ID string `protobuf:"bytes,1,opt,name=ID,oneof"`
}
type ResourceIDRequest_Name struct {
	Name string `protobuf:"bytes,2,opt,name=Name,oneof"`
}

func (*ResourceIDRequest_ID) isResourceIDRequest_Key()   {}
func (*ResourceIDRequest_Name) isResourceIDRequest_Key() {}

func (m *ResourceIDRequest) GetKey() isResourceIDRequest_Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ResourceIDRequest) GetID() string {
	if x, ok := m.GetKey().(*ResourceIDRequest_ID); ok {
		return x.ID
	}
	return ""
}

func (m *ResourceIDRequest) GetName() string {
	if x, ok := m.GetKey().(*ResourceIDRequest_Name); ok {
		return x.Name
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ResourceIDRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ResourceIDRequest_OneofMarshaler, _ResourceIDRequest_OneofUnmarshaler, _ResourceIDRequest_OneofSizer, []interface{}{
		(*ResourceIDRequest_ID)(nil),
		(*ResourceIDRequest_Name)(nil),
	}
}

func _ResourceIDRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ResourceIDRequest)
	// Key
	switch x := m.Key.(type) {
	case *ResourceIDRequest_ID:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.ID)
	case *ResourceIDRequest_Name:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Name)
	case nil:
	default:
		return fmt.Errorf("ResourceIDRequest.Key has unexpected type %T", x)
	}
	return nil
}

func _ResourceIDRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ResourceIDRequest)
	switch tag {
	case 1: // Key.ID
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Key = &ResourceIDRequest_ID{x}
		return true, err
	case 2: // Key.Name
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Key = &ResourceIDRequest_Name{x}
		return true, err
	default:
		return false, nil
	}
}

func _ResourceIDRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ResourceIDRequest)
	// Key
	switch x := m.Key.(type) {
	case *ResourceIDRequest_ID:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.ID)))
		n += len(x.ID)
	case *ResourceIDRequest_Name:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Name)))
		n += len(x.Name)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*RunRequest)(nil), "api.RunRequest")
	proto.RegisterType((*RunReply)(nil), "api.RunReply")
	proto.RegisterType((*StopTaskRequest)(nil), "api.StopTaskRequest")
	proto.RegisterType((*StopTaskReply)(nil), "api.StopTaskReply")
	proto.RegisterType((*CreateRequest)(nil), "api.CreateRequest")
	proto.RegisterType((*CreateReply)(nil), "api.CreateReply")
	proto.RegisterType((*StartRequest)(nil), "api.StartRequest")
	proto.RegisterType((*StartReply)(nil), "api.StartReply")
	proto.RegisterType((*ResourceRequest)(nil), "api.ResourceRequest")
	proto.RegisterType((*ResourceReply)(nil), "api.ResourceReply")
	proto.RegisterType((*ResourceIDRequest)(nil), "api.ResourceIDRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Instance service

type InstanceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error)
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartReply, error)
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunReply, error)
	StopTask(ctx context.Context, in *StopTaskRequest, opts ...grpc.CallOption) (*StopTaskReply, error)
}

type instanceClient struct {
	cc *grpc.ClientConn
}

func NewInstanceClient(cc *grpc.ClientConn) InstanceClient {
	return &instanceClient{cc}
}

func (c *instanceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error) {
	out := new(CreateReply)
	err := grpc.Invoke(ctx, "/api.Instance/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartReply, error) {
	out := new(StartReply)
	err := grpc.Invoke(ctx, "/api.Instance/Start", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunReply, error) {
	out := new(RunReply)
	err := grpc.Invoke(ctx, "/api.Instance/Run", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceClient) StopTask(ctx context.Context, in *StopTaskRequest, opts ...grpc.CallOption) (*StopTaskReply, error) {
	out := new(StopTaskReply)
	err := grpc.Invoke(ctx, "/api.Instance/StopTask", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Instance service

type InstanceServer interface {
	Create(context.Context, *CreateRequest) (*CreateReply, error)
	Start(context.Context, *StartRequest) (*StartReply, error)
	Run(context.Context, *RunRequest) (*RunReply, error)
	StopTask(context.Context, *StopTaskRequest) (*StopTaskReply, error)
}

func RegisterInstanceServer(s *grpc.Server, srv InstanceServer) {
	s.RegisterService(&_Instance_serviceDesc, srv)
}

func _Instance_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Instance/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Instance_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Instance/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Instance_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Instance/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Instance_StopTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceServer).StopTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Instance/StopTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceServer).StopTask(ctx, req.(*StopTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Instance_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Instance",
	HandlerType: (*InstanceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Instance_Create_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _Instance_Start_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _Instance_Run_Handler,
		},
		{
			MethodName: "StopTask",
			Handler:    _Instance_StopTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1.proto",
}

// Client API for Resource service

type ResourceClient interface {
	Register(ctx context.Context, in *ResourceRequest, opts ...grpc.CallOption) (*ResourceReply, error)
	Unregister(ctx context.Context, in *ResourceIDRequest, opts ...grpc.CallOption) (*ResourceReply, error)
}

type resourceClient struct {
	cc *grpc.ClientConn
}

func NewResourceClient(cc *grpc.ClientConn) ResourceClient {
	return &resourceClient{cc}
}

func (c *resourceClient) Register(ctx context.Context, in *ResourceRequest, opts ...grpc.CallOption) (*ResourceReply, error) {
	out := new(ResourceReply)
	err := grpc.Invoke(ctx, "/api.Resource/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceClient) Unregister(ctx context.Context, in *ResourceIDRequest, opts ...grpc.CallOption) (*ResourceReply, error) {
	out := new(ResourceReply)
	err := grpc.Invoke(ctx, "/api.Resource/Unregister", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Resource service

type ResourceServer interface {
	Register(context.Context, *ResourceRequest) (*ResourceReply, error)
	Unregister(context.Context, *ResourceIDRequest) (*ResourceReply, error)
}

func RegisterResourceServer(s *grpc.Server, srv ResourceServer) {
	s.RegisterService(&_Resource_serviceDesc, srv)
}

func _Resource_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Resource/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServer).Register(ctx, req.(*ResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resource_Unregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServer).Unregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Resource/Unregister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServer).Unregister(ctx, req.(*ResourceIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Resource_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Resource",
	HandlerType: (*ResourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Resource_Register_Handler,
		},
		{
			MethodName: "Unregister",
			Handler:    _Resource_Unregister_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1.proto",
}

func init() { proto.RegisterFile("v1.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 491 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xad, 0x9d, 0xb6, 0x72, 0x27, 0x84, 0x34, 0x4b, 0x85, 0x22, 0x03, 0x2a, 0xb2, 0x90, 0x40,
	0x48, 0x75, 0x4a, 0x90, 0x38, 0x70, 0x0c, 0x39, 0x60, 0x01, 0x3d, 0xb8, 0x81, 0x03, 0x17, 0xb4,
	0x89, 0x47, 0x89, 0xd5, 0x78, 0x77, 0xb1, 0xd7, 0x11, 0xb9, 0xf0, 0x85, 0x7c, 0x0e, 0xdc, 0xd1,
	0x7a, 0x77, 0x6b, 0x3b, 0xa0, 0x2a, 0xc7, 0x7d, 0xf3, 0xe6, 0xbd, 0x97, 0x99, 0x89, 0xc1, 0xdb,
	0xbc, 0x0a, 0x45, 0xce, 0x25, 0x27, 0x1d, 0x2a, 0x52, 0xbf, 0x9b, 0xf1, 0x04, 0xd7, 0x1a, 0x09,
	0xe6, 0x00, 0x71, 0xc9, 0x62, 0xfc, 0x5e, 0x62, 0x21, 0xc9, 0x63, 0x38, 0x49, 0x33, 0xba, 0xc4,
	0x2b, 0x9a, 0xe1, 0xd0, 0x79, 0xea, 0xbc, 0x38, 0x89, 0x6b, 0x80, 0xf8, 0xe0, 0xad, 0x78, 0x21,
	0xab, 0xa2, 0x5b, 0x15, 0x6f, 0xdf, 0xaa, 0x26, 0x69, 0x71, 0x33, 0xdb, 0x0a, 0x1c, 0x76, 0x74,
	0xcd, 0xbe, 0x83, 0x8f, 0xe0, 0x55, 0x1e, 0x62, 0xbd, 0x25, 0xe7, 0xd0, 0x4d, 0x59, 0x21, 0x29,
	0x5b, 0xe0, 0xb7, 0x34, 0x31, 0x1e, 0x60, 0xa1, 0x28, 0x51, 0x84, 0x1c, 0x0b, 0x5e, 0xe6, 0x9a,
	0xa0, 0x7d, 0xc0, 0x42, 0x51, 0x12, 0x44, 0xd0, 0xbf, 0x96, 0x5c, 0xcc, 0x68, 0x71, 0x63, 0x63,
	0x37, 0x83, 0x39, 0x77, 0x04, 0x73, 0x77, 0x82, 0x5d, 0x42, 0xaf, 0x96, 0xda, 0x27, 0x9d, 0xea,
	0x78, 0x97, 0x23, 0x95, 0x68, 0xad, 0x77, 0xe2, 0x3a, 0xff, 0xc4, 0x0d, 0xa1, 0x6b, 0x3b, 0xf6,
	0x72, 0x18, 0xc1, 0xbd, 0x6b, 0x49, 0x73, 0xd9, 0x30, 0xb8, 0xbb, 0xe1, 0x02, 0xc0, 0x34, 0xec,
	0xa5, 0xcf, 0xa1, 0x1f, 0x9b, 0x74, 0xd6, 0xe2, 0x25, 0x1c, 0x32, 0xce, 0x70, 0xf8, 0x5b, 0x2d,
	0xae, 0x3b, 0x7e, 0x10, 0xea, 0x03, 0xb9, 0xe2, 0x0c, 0x67, 0x98, 0x89, 0x35, 0x95, 0xf8, 0xfe,
	0x20, 0xae, 0x38, 0xe4, 0x19, 0xb8, 0x9b, 0x6c, 0xf8, 0x47, 0x33, 0x07, 0x86, 0xf9, 0xe5, 0x53,
	0x83, 0xe7, 0x6e, 0xb2, 0x09, 0x80, 0x67, 0x91, 0xe0, 0x1c, 0x7a, 0xb5, 0xa1, 0x8a, 0x78, 0x1f,
	0xdc, 0x68, 0x6a, 0x92, 0xb9, 0xd1, 0x34, 0x98, 0xc0, 0xc0, 0x12, 0xa2, 0xa9, 0xcd, 0x74, 0x5a,
	0x93, 0x94, 0x66, 0x34, 0x25, 0x67, 0x70, 0x58, 0x5f, 0x9e, 0xca, 0xa3, 0x5e, 0x93, 0x23, 0xe8,
	0x7c, 0xc0, 0xed, 0xf8, 0x97, 0x03, 0x5e, 0x64, 0x7e, 0x24, 0xb9, 0x84, 0x63, 0x3d, 0x72, 0x42,
	0x42, 0x2a, 0xd2, 0xb0, 0xb5, 0x31, 0xff, 0xb4, 0x85, 0x89, 0xf5, 0x36, 0x38, 0x20, 0x17, 0x70,
	0x54, 0xcd, 0x90, 0x0c, 0xaa, 0x62, 0x73, 0x01, 0x7e, 0xbf, 0x09, 0x69, 0xfa, 0x73, 0xe8, 0xc4,
	0x25, 0x23, 0xba, 0x52, 0xff, 0x7d, 0xfc, 0x5e, 0x0d, 0x68, 0xe2, 0x1b, 0xf0, 0xec, 0x81, 0x91,
	0x33, 0xa3, 0xd3, 0x3a, 0x5d, 0x9f, 0xec, 0xa0, 0x55, 0xdf, 0xf8, 0x27, 0x78, 0x76, 0x24, 0x4a,
	0x23, 0xc6, 0x65, 0x5a, 0x48, 0xcc, 0x8d, 0xc6, 0xce, 0xfe, 0x8c, 0x46, 0x6b, 0xc8, 0xc1, 0x01,
	0x79, 0x0b, 0xf0, 0x99, 0xe5, 0xb6, 0xf3, 0x61, 0x8b, 0x73, 0x3b, 0xe7, 0xff, 0xf7, 0x4e, 0x9e,
	0x7c, 0x7d, 0xb4, 0x4c, 0xe5, 0xaa, 0x9c, 0x87, 0x0b, 0x9e, 0x8d, 0xe8, 0x8f, 0x62, 0x35, 0xe2,
	0x02, 0xd9, 0x26, 0x59, 0x8c, 0xa8, 0x48, 0xe7, 0xc7, 0xd5, 0xb7, 0xe3, 0xf5, 0xdf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x09, 0x56, 0xce, 0xcb, 0x59, 0x04, 0x00, 0x00,
}
